# Generated by Django 3.1.1 on 2022-05-24 20:20

from django.db import migrations, models
import django.db.models.deletion
import personas.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.persona')),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('foto', models.ImageField(null=True, upload_to=personas.models.cargarFoto)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.genero')),
            ],
            bases=('personas.persona',),
        ),
    ]
