# Generated by Django 3.1.1 on 2022-05-25 20:51

from django.db import migrations, models
import personas.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to=personas.models.cargarFotoProducto)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
